# version: '2'

# services:
#   app:
#     image: ulexus/meteor
#     ports:
#     - "80:80"
#     links:
#     - db
#     environment:
#       REPO: 'https://github.com/jdnietovunal/criptografia'
#       ROOT_URL: 'http://35.231.250.182'
#   db:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_DB: criptapp
#       POSTGRES_USER: jdnietov
#       POSTGRES_PASSWORD: password
#     ports:
#       - 5432:5432

# version: '2'

# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     links:
#       - db
#   db:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_DB: criptapp
#       POSTGRES_USER: jdnietov
#       POSTGRES_PASSWORD: password
#     ports:
#       - 5432:5432

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    links:
      - db
    environment:
      ROOT_URL: 'http://192.168.99.101'

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: criptapp
      POSTGRES_USER: jdnietov
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432